/* Doorstop */
RAISERROR(N'Did you mean to run the whole thing?',20,1) WITH LOG;
GO


/*************************************************
🌟📋 SIMPLE STRESS TESTING 📋🌟


-----------------------------------------------------------
Let's generate some scalar functions and stored procedures in our database.
One could also capture a trace to replay in the case you have a real application.
*************************************************/

/* Configure the instance */
exec sp_configure 'show advanced options', 1;
GO
RECONFIGURE
GO
exec sp_configure 'max degree of parallelism', 4;
GO

exec sp_configure 'cost threshold for parallelism', 50;
GO
RECONFIGURE
GO


/*************************************************
This code was generated by GitHub Copilot. I specified that I wanted some 
scalar UDFs to be in use. These procs may not all do what their names imply or 
work properly, I only wanted a repeatable workload.
*************************************************/

USE StackOverflow2010;
GO

/* Enable Query Store */

ALTER DATABASE CURRENT
SET QUERY_STORE = ON
    (
      OPERATION_MODE = READ_WRITE,
      CLEANUP_POLICY = ( STALE_QUERY_THRESHOLD_DAYS = 90 ),
      DATA_FLUSH_INTERVAL_SECONDS = 900,
      MAX_STORAGE_SIZE_MB = 1024,
      INTERVAL_LENGTH_MINUTES = 60,
      SIZE_BASED_CLEANUP_MODE = AUTO,
      MAX_PLANS_PER_QUERY = 200,
      WAIT_STATS_CAPTURE_MODE = ON
    );



/* Begin creating programmable objects */

	--Scalar UDFs
	CREATE OR ALTER FUNCTION dbo.GetAnswerCount(@QuestionId INT)
	RETURNS INT
	AS
	BEGIN
		DECLARE @AnswerCount INT
		SELECT @AnswerCount = COUNT(*) FROM dbo.Posts 
		WHERE 
			ParentId = @QuestionId
			and PostTypeId=2;
		RETURN @AnswerCount;
	END;
	GO

	CREATE OR ALTER FUNCTION dbo.GetCommentCount(@PostId INT)
	RETURNS INT
	AS
	BEGIN
		DECLARE @CommentCount INT
		SELECT @CommentCount = COUNT(*) FROM dbo.Comments 
		WHERE PostId = @PostId;
		RETURN @CommentCount;
	END;
	GO

	CREATE OR ALTER FUNCTION dbo.GetVoteCount(@PostId INT)
	RETURNS INT
	AS
	BEGIN
		DECLARE @VoteCount INT
		SELECT @VoteCount = SUM(VoteTypeId) 
		FROM dbo.Votes WHERE 
		PostId = @PostId;
		RETURN @VoteCount;
	END;
	GO

	-- Stored procedures
	CREATE OR ALTER PROCEDURE dbo.GetTopQuestionsByTag(@TagName NVARCHAR(50))
	AS
	BEGIN
		SELECT TOP 10 q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 
		ORDER BY q.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetCommentsByUser(@UserId INT)
	AS
	BEGIN
		SELECT c.Id, c.Text, dbo.GetVoteCount(c.Id) AS VoteCount
		FROM dbo.Comments c
		WHERE c.UserId = @UserId
		ORDER BY c.CreationDate DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetAnswersByQuestion(@QuestionId INT)
	AS
	BEGIN
		SELECT a.Id, a.Body, dbo.GetCommentCount(a.Id) AS CommentCount, dbo.GetVoteCount(a.Id) AS VoteCount
		FROM dbo.Posts a
		WHERE a.ParentId = @QuestionId
			and a.PostTypeId=2
		ORDER BY a.Score DESC;
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByUser(@UserId INT)
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.PostTypeId = 1 
			AND q.OwnerUserId = @UserId
		ORDER BY q.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopUsersByReputation
	AS
	BEGIN
		SELECT TOP 10 u.Id, u.DisplayName, u.Reputation, dbo.GetAnswerCount(u.Id) AS AnswerCount, dbo.GetVoteCount(u.Id) AS VoteCount
		FROM dbo.Users u
		ORDER BY u.Reputation DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByTagAndUser(@TagName NVARCHAR(50), @UserId INT)
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 AND q.OwnerUserId = @UserId 
		ORDER BY q.Score DESC;
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetCommentsByPost(@PostId INT)
	AS
	BEGIN
		SELECT c.Id, c.Text, dbo.GetVoteCount(c.Id) AS VoteCount
		FROM dbo.Comments c
		WHERE c.PostId = @PostId
		ORDER BY c.CreationDate DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopQuestionsByUser(@UserId INT)
	AS
	BEGIN
		SELECT TOP 10 q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.PostTypeId = 1 AND q.OwnerUserId = @UserId
		ORDER BY q.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetAnswersByUser(@UserId INT)
	AS
	BEGIN
		SELECT a.Id, a.Body, dbo.GetCommentCount(a.Id) AS CommentCount, dbo.GetVoteCount(a.Id) AS VoteCount
		FROM dbo.Posts a
		WHERE a.OwnerUserId = @UserId
			and a.PostTypeId=2
		ORDER BY a.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByTag(@TagName NVARCHAR(50))
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1
		ORDER BY q.Score DESC;
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopUsersByAnswerCount
	AS
	BEGIN
		SELECT TOP 10 u.Id, u.DisplayName, u.Reputation, COUNT(*) AS AnswerCount
		FROM dbo.Users u
		INNER JOIN dbo.Posts a ON u.Id = a.OwnerUserId
		WHERE a.PostTypeId = 2
		GROUP BY u.Id, u.DisplayName, u.Reputation
		ORDER BY AnswerCount DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByTitle(@Title NVARCHAR(100))
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.PostTypeId = 1 AND q.Title LIKE '%' + @Title + '%'
		ORDER BY q.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopTagsByQuestionCount
	AS
	BEGIN
		SELECT TOP 10 SUBSTRING(Tags, CHARINDEX('<', Tags) + 1, CHARINDEX('>', Tags) - CHARINDEX('<', Tags) - 1) AS TagName, COUNT(*) AS QuestionCount
		FROM dbo.Posts
		WHERE PostTypeId = 1 
		GROUP BY SUBSTRING(Tags, CHARINDEX('<', Tags) + 1, CHARINDEX('>', Tags) - CHARINDEX('<', Tags) - 1)
		ORDER BY QuestionCount DESC;
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopUsersByQuestionCount
	AS
	BEGIN
		SELECT TOP 10 u.Id, u.DisplayName, u.Reputation, COUNT(*) AS QuestionCount
		FROM dbo.Users u
		INNER JOIN dbo.Posts q ON u.Id = q.OwnerUserId
		WHERE q.PostTypeId = 1
		GROUP BY u.Id, u.DisplayName, u.Reputation
		ORDER BY QuestionCount DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetAnswersByTag(@TagName NVARCHAR(50))
	AS
	BEGIN
		SELECT a.Id, a.Body, dbo.GetCommentCount(a.Id) AS CommentCount, dbo.GetVoteCount(a.Id) AS VoteCount
		FROM dbo.Posts q
		INNER JOIN dbo.Posts a ON q.Id = a.ParentId
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 AND a.PostTypeId = 2 
		ORDER BY a.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopTagsByCommentCount
	AS
	BEGIN
		SELECT TOP 10 u.Id, u.DisplayName, u.Reputation, COUNT(*) AS CommentCount
		FROM dbo.Users u
		INNER JOIN dbo.Comments c ON u.Id = c.UserId
		INNER JOIN dbo.Posts q ON c.PostId = q.Id
		WHERE q.PostTypeId = 1 
		GROUP BY u.Id, u.DisplayName, u.Reputation
		ORDER BY CommentCount DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetTopUsersByCommentCount
	AS
	BEGIN
		SELECT TOP 10 u.Id, u.DisplayName, u.Reputation, COUNT(*) AS CommentCount
		FROM dbo.Users u
		INNER JOIN dbo.Comments c ON u.Id = c.UserId
		GROUP BY u.Id, u.DisplayName, u.Reputation
		ORDER BY CommentCount DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByTagAndTitle(@TagName NVARCHAR(50), @Title NVARCHAR(100))
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 AND q.Title LIKE '%' + @Title + '%' 
		ORDER BY q.Score DESC
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetAnswersByTagAndUser(@TagName NVARCHAR(50), @UserId INT)
	AS
	BEGIN
		SELECT a.Id, a.Body, dbo.GetCommentCount(a.Id) AS CommentCount, dbo.GetVoteCount(a.Id) AS VoteCount
		FROM dbo.Posts q
		INNER JOIN dbo.Posts a ON q.Id = a.ParentId
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 AND a.PostTypeId = 2 AND a.OwnerUserId = @UserId 
		ORDER BY a.Score DESC;
	END;
	GO

	CREATE OR ALTER PROCEDURE dbo.GetQuestionsByTagAndUserAndTitle(@TagName NVARCHAR(50), @UserId INT, @Title NVARCHAR(100))
	AS
	BEGIN
		SELECT q.Id, q.Title, dbo.GetAnswerCount(q.Id) AS AnswerCount, dbo.GetVoteCount(q.Id) AS VoteCount
		FROM dbo.Posts q
		WHERE q.Tags LIKE '%' + @TagName + '%' AND q.PostTypeId = 1 AND q.OwnerUserId = @UserId AND q.Title LIKE '%' + @Title + '%' 
		ORDER BY q.Score DESC;
	END;
	GO

/* End creating programmable objects */

/* Create some basic nonclustered indexes.
These will take ~41 seconds to create on the demo macbook air*/

USE [StackOverflow2010]
GO
CREATE NONCLUSTERED INDEX ix_Comments_UserId
ON [dbo].[Comments] ([UserId])
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX ix_Comments_PostId_INCLUDES
ON [dbo].[Comments] ([PostId]) INCLUDE (UserId)
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX ix_Posts_OwnerUserId_PostTypeId
ON [dbo].[Posts] ([OwnerUserId],[PostTypeId])
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX ix_Posts_PostTypeId_Title_INCLUDES
ON [dbo].[Posts] ([PostTypeId],[Title]) INCLUDE ([Score])
WITH (DATA_COMPRESSION = PAGE);

CREATE NONCLUSTERED INDEX ix_Posts_PostTypeId_Tags_INCLUDES
ON [dbo].[Posts] (PostTypeId,Tags) INCLUDE (Score, ParentId)
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX ix_Posts_ParentId_PostTypeId
ON [dbo].[Posts] ([ParentId],[PostTypeId])
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX ix_Votes_PostId
ON [dbo].Votes (PostId)
WITH (DATA_COMPRESSION = PAGE);
GO


/* Example calls to the procedures 
We don't need to run these manually, we'll be calling them via ostress.exe
*/
ALTER DATABASE SCOPED CONFIGURATION CLEAR PROCEDURE_CACHE;
GO

EXEC dbo.GetTopQuestionsByTag 'mongodb'
EXEC dbo.GetTopQuestionsByTag 'javascript'

EXEC dbo.GetAnswersByQuestion 1
EXEC dbo.GetAnswersByQuestion 23930

EXEC dbo.GetQuestionsByUser 10
EXEC dbo.GetQuestionsByUser 147601

EXEC dbo.GetCommentsByUser 68183
EXEC dbo.GetCommentsByUser 100

EXEC dbo.GetTopUsersByReputation

EXEC dbo.GetQuestionsByTagAndUser 'xml', 147
EXEC dbo.GetQuestionsByTagAndUser 'javascript', 147601

EXEC dbo.GetCommentsByPost 1322
EXEC dbo.GetCommentsByPost 13

EXEC dbo.GetTopQuestionsByUser 1
EXEC dbo.GetTopQuestionsByUser 68183

EXEC dbo.GetAnswersByUser 68183
EXEC dbo.GetAnswersByUser 1

EXEC dbo.GetQuestionsByTag 'VB4'
EXEC dbo.GetQuestionsByTag 'javascript'

EXEC dbo.GetTopUsersByAnswerCount

EXEC dbo.GetQuestionsByTitle 'Visual Basic'
EXEC dbo.GetQuestionsByTitle 'js'


EXEC dbo.GetTopTagsByQuestionCount
EXEC dbo.GetTopUsersByQuestionCount

EXEC dbo.GetAnswersByTag 'fortran'
EXEC dbo.GetAnswersByTag 'c#'

EXEC dbo.GetTopTagsByCommentCount
EXEC dbo.GetTopUsersByCommentCount

EXEC dbo.GetQuestionsByTagAndTitle 'cobol', 'error'
EXEC dbo.GetQuestionsByTagAndTitle 'javascript', 'node.js'

EXEC dbo.GetAnswersByTagAndUser 'meta', 1
EXEC dbo.GetQuestionsByTagAndUserAndTitle 'javascript', 2138, 'node.js'


/* Download and install the RML utilities to get ostress.exe
https://www.microsoft.com/en-us/download/details.aspx?id=103126

Add the directory where you installed the tools (C:\Program Files\Microsoft Corporation\RMLUtils) to the path
Restart SSMS after adding it to the path
*/

/*

Notes:
I'm  using -T146 because I can't see how to add ;TrustServerCertificate=true to the connection string.
This is using an unencrypted connection.
I copied mistakes_02-workload.sql in the Windows VM where I am running the workload for simplicity as absolute ACLs out to my mac weren't working.
*/

-- First we are going to test in compat level 140
ALTER DATABASE StackOverflow2010 SET COMPATIBILITY_LEVEL = 140;
GO

SELECT name, compatibility_level
FROM sys.databases;
GO


--Run in another window --  Enable SQLCMD mode for the session in SSMS (Query menu) 
--With my macbook air setup this takes ~6 minutes
!!ostress.exe -S192.168.4.181,1435 -dStackOverflow2010 -Usa -PPassword23 -q -n4 -r2 -i"C:\Temp\mistakes_02-workload.sql" -T146


/* while it's running */
exec sp_WhoIsActive @get_plans=1, @get_outer_command=1;

exec sp_BlitzWho @ExpertMode=1, @GetLiveQueryPlan=1;


/* After it completes, raise the compatibility level. Then re-run the workload */
ALTER DATABASE StackOverflow2010 SET COMPATIBILITY_LEVEL = 160;
GO

/* Some data for existing plans, like compat level last seen, appears to be updated when query store flushes to disk */
exec sp_query_store_flush_db;
GO

/* Examine the changes in plans in the Query Store built in views, or with QuickieStore from Erik Darling.
https://github.com/erikdarlingdata/DarlingData/blob/main/sp_QuickieStore/sp_QuickieStore.sql
*/
exec sp_QuickieStore @expert_mode=1;
GO


exec sp_QuickieStore @expert_mode=1, @include_plan_ids=33;
GO

/*Example of memory grant feedback for a plan.
https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-query-store-plan-feedback

[{"NodeId":"4","AdditionalMemoryKB":"15040","Count":"5","Average":"13728972","Variance":"528837649221"},{"NodeId":"6","AdditionalMemoryKB":"4312","Count":"5","Average":"4674355","Variance":"167335642471"}]
*/

SELECT * 
FROM 
sys.query_store_plan_feedback
order by plan_id, feature_id, create_time, last_updated_time;