/* Doorstop */
RAISERROR(N'Did you mean to run the whole thing?',20,1) WITH LOG;
GO


/*************************************************

🌟📋 STACK DUMPS 📋🌟

I'm a huge believer in being able to reproduce issues outside of production whenever we can.
This can help ensure that we are familiar with how things will look, as well as test monitoring
systems to ensure they pick up on these problems.

Let's cause a stack dump generated by a specific error. 
We'll use a deadlock because it's easy to generate, but you wouldn't want to do this in production.

-----------------------------------------------------------

https://learn.microsoft.com/en-US/troubleshoot/sql/tools/use-sqldumper-generate-dump-file#dbccstackdump

"The DBCC STACKDUMP command can help you create a memory dump in the LOG directory of your SQL Server instance installation. 
The command will by default create a minidump with all threads, which has limited size and is adequate to reflect the state 
of SQL Server process."

https://learn.microsoft.com/en-US/troubleshoot/sql/tools/use-sqldumper-generate-dump-file#extended-dbcc-stackdump-functionality-introduced-in-sql-server-2019

Starting with SQL Server 2019 CU2, the DBCC STACKDUMP command was extended to support generating dumps of different types: mini, filtered, full dumps. 
This command eliminates the need for using trace flags.

***********************************************************/

DBCC TRACEON(2551, -1)
GO


DBCC STACKDUMP;
GO

/*************************************************

🌟📋  GENERATING A STACK DUMP ON A SPECIFIC ERROR, SUCH AS A DEADLOCK 📋🌟

-----------------------------------------------------------
https://techcommunity.microsoft.com/t5/sql-server-support-blog/how-it-works-sql-server-engine-error-messages/ba-p/315433

"Most errors can be used to trigger extended diagnostics.   The -y#### command line parameter can be used to trigger a mini-dump when the error is encountered.  
For example -y1205 would capture a mini-dump each time a deadlock was encountered. 
Additional information will be placed in the error log as well as the LOG directory for the instance.""

The dbcc dumptrigger('set' | 'clear', ###) command can be used to dynamically enabled and disable the -y behavior.   

For example dbcc dumptrigger('set', 1205) is the same as -y1205 but does not require the SQL Server service to be restarted. 

https://learn.microsoft.com/en-US/troubleshoot/sql/tools/use-sqldumper-generate-dump-file#dbccstackdump

*/


DBCC DUMPTRIGGER('set', 1205);
GO


/* Cause a deadlock */

/* We will need two sessions to cause a deadlock.
Session 1 */
USE StackOverflow2010;
GO

BEGIN TRANSACTION;

    UPDATE dbo.Users
    SET Reputation = Reputation + 100
    WHERE Id = 557499;


-- Session 2
USE StackOverflow2010;
GO
BEGIN TRANSACTION;

    UPDATE dbo.Users
    SET Reputation = Reputation - 100
    WHERE Id = 209984;

    UPDATE dbo.Users
    SET Reputation = Reputation + 100
    WHERE Id = 557499;

ROLLBACK

/* 
Session 1 (continued)
Attempt to update a different column in the same row that session 2 is updating.
This should cause a deadlock to fire within 30 seconds.
*/
    UPDATE dbo.Users
    SET Reputation = Reputation + 100
    WHERE Id = 209984;



/* 
Session 1 (in case it's not chosen as the deadlock victim)
*/
ROLLBACK;

/* Review the error log for the stack dump */


/* Reset */

DBCC DUMPTRIGGER('clear', 1205);
GO


/*************************************************

🌟📋 sp_LogHunter from Erik Darling 📋🌟

https://github.com/erikdarlingdata/DarlingData/blob/main/sp_LogHunter/sp_LogHunter.sql
**************************************************/

EXEC sp_LogHunter;
GO


EXEC sp_LogHunter @custom_message='recovery is complete' ;
GO



/*************************************************

🌟📋 Capturing Deadlocks with Extended Events 📋🌟

**************************************************/



/* Deadlocks are written to the system_health Extended Events trace automatically

We can query that ourselves or slice and dice it with a free tool like Erik Darling's sp_HealthParser
https://github.com/erikdarlingdata/DarlingData/blob/main/sp_HealthParser/sp_HealthParser.sql

*/

exec sp_HealthParser;


/* It can be convenient and sometimes safer to persist deadlock data to a separate trace that uses a file 
for longer term storage, if we don't have this being picked up by a monitoring system.

There is slightly different syntax and considerations for Azure SQL Database:
    https://learn.microsoft.com/en-us/azure/azure-sql/database/analyze-prevent-deadlocks?view=azuresql&tabs=ring-buffer
    Essentially, use sqlserver.database_xml_deadlock_report and create the session ON DATABASE
        instead of sqlserver.xml_deadlock_report and creating the session ON SERVER
*/

CREATE EVENT SESSION [Deadlocks] ON SERVER 
ADD EVENT sqlserver.xml_deadlock_report
ADD TARGET package0.event_file(SET filename=N'/var/opt/mssql/log/Deadlocks.xel')
WITH (STARTUP_STATE=ON, MAX_MEMORY=4 MB)
GO

ALTER EVENT SESSION [Deadlocks] ON SERVER
    STATE = START;
GO

/* Reproduce the deadlock using the code above */

ALTER EVENT SESSION [Deadlocks] ON SERVER
    STATE = STOP;
GO

DROP EVENT SESSION Deadlocks ON SERVER;
GO

/* Mini-dump experimental analaysis by Sean Gallardy */
https://www.seangallardy.com/
https://www.sqldumpanalysis.com/


/**************************************************************** 
OTHER THINGS TO DOCUMENT AND KNOW:
*****************************************************************/

/* 
Informative settings:
	Max degree of paralellism
	Cost threshold for parallelism

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit

sp_blitz will help you look for goofs like changing these settings and more:
	Fill factor % -- leave this at the default please
	Max worker threads -- leave this at the default please
*/
select *
from sys.configurations;

exec sp_Blitz;
GO

/* Database compatibility level
Understand which Intelligent Query Processing features are enabled or disabled at
your current compatibility level
*/
SELECT name, compatibility_level, *
FROM sys.databases;
GO



SELECT *
FROM sys.database_scoped_configurations;
GO


SELECT *
FROM sys.database_automatic_tuning_options;
GO

